name: CICD

on:
  push:
    branches: [devops-web-deploy-to-ec2]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        #run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u mamad.diouf@gmail.com -p souleyE599@@
      - name: Build docker image
        run: docker build -t mamaddiouf/devops-service .
      - name: Publish image to docker hub
        run: docker push mamaddiouf/devops-service:latest

