name: CICD

on:
  push:
    branches: [devops-web-deploy-to-ec2]
jobs:
  build:
    runs-on: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./devops-service
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t mamaddiouf/devops-service .
      - name: Publish image to docker hub
        run: docker push mamaddiouf/devops-service:latest

  deploy:
    needs: build
    runs-on: [ devops-web-deploy-aws-ec2 ]
    steps:
      - name: Check that the image builds
        uses: actions/checkout@v4
      - name: Pull image docker from repository
        run: docker pull docker:latest
      - name: Pull Image from docker hub
        run: docker pull mamaddiouf/devops-service:latest
      - name: Delete old container
        run: docker rm -f mamaddiouf/devops-service
      - name: Run docker compose up
        run: docker-compose up



